---
title: "Delivery"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(readxl)
library(lubridate)
library(stringr)
library(DT)
library(ggpubr)

Delivery_Racc <- read_excel("mock-data.xlsx")
Delivery_Racc$Arrivo <- ymd(Delivery_Racc$Arrivo)
Delivery_Racc$Scadenza <- ymd(Delivery_Racc$Scadenza)

# deadline for sequenzes
SC_A <- ymd("2019-05-31")
SC_B <- ymd("2019-05-29")
SC_C <- ymd("2019-05-30")

Delivery_Racc$Scadono <- ifelse(Delivery_Racc$Seq == "A", Delivery_Racc$Scadenza <= SC_A,
                               ifelse(Delivery_Racc$Seq == "B", Delivery_Racc$Scadenza <= SC_B, 
                                      Delivery_Racc$Scadenza <= SC_C))
Delivery_Racc <- Delivery_Racc %>%
  mutate(Scadono = ifelse(Scadono == TRUE, "SI", "NO"))

Scad <- Delivery_Racc %>%
  filter(Scadono == "SI")

Delivery_Cert <- read_excel("Certificate.xlsx")
```

Plot {data-icon="fa-signal"}
===========================================================

Row {data-height=100}
----------------------------------------------
### Delivery-Racc

```{r echo=FALSE}
nrRacc <- Delivery_Racc %>% count()
valueBox(nrRacc, icon = "fa-archive")
```

### Expiring Delivery-Racc

```{r echo=FALSE}
raccScad <- Delivery_Racc %>%
  filter(Scadono == "SI") %>%
  count()
valueBox(raccScad, icon = "fa-hourglass-half", color = "warning")
```

### Delivery-Cert

```{r echo=FALSE}
nrCert <- Delivery_Cert %>% count()
valueBox(nrCert, icon = "fa-envelope")
```

### Expiring Delivery-Cert

```{r echo=FALSE}
certNO <- Delivery_Cert %>%
  filter(Esito == "NO") %>%
  count()
valueBox(certNO, icon = "fa-exclamation", color = "warning")
```

### Last Update

```{r echo=FALSE}
valueBox(substr(now(), 6, 16))
```

Row
----------------------------------------------

### Delivery-Racc Plot

```{r echo=FALSE}
grpost <- Delivery_Racc %>%
  group_by(Postino, Seq, Scadono) %>%
  count()

ggdotchart(grpost, x = "Postino", y = "n",
           color = "Scadono",
           add = "segments",
           rotate = TRUE,
           group = "Postino",
           facet.by = "Seq",
           xlab = FALSE,
           ylab = FALSE,
           dot.size = 8,
           label = round(grpost$n),
           font.label = list(color = "white", size = 9, 
                             vjust = 0.5))

```

### Delivery-Cert Plot

```{r echo=FALSE}

grCert <- Delivery_Cert %>%
  group_by(Postino, Esito) %>%
  count()

ggdotchart(grCert, x = "Postino", y = "n",
           color = "Esito",
           sorting = "descending",
           add = "segments",
           rotate = TRUE,
           group = "Esito",
           xlab = FALSE,
           ylab = FALSE,
           facet.by = "Esito",
           dot.size = 10,
           label = round(grCert$n),
           font.label = list(color = "black", size = 8, 
                             vjust = 0.5))
```

Expiring Delivery-Racc
===============================================================================

```{r echo=FALSE}
Scad$Giro <- as.factor(Scad$Giro)
Scad$Seq <- as.factor(Scad$Seq)
Scad$Postino <- as.factor(Scad$Postino)

Scad[is.na(Scad)] <- ""
Scad$Indirizzo <- str_c(Scad$Via, Scad$`N°`, sep = " ")

tabela <- Scad %>%
  select("Barcode", "Nome Dest.", "Indirizzo", "Giro",
             "Seq", "Postino")

datatable(tabela, 
          class = 'compact nowrap',
          extensions = c('Buttons', 'Responsive'),
          filter = 'top', 
          options = list(
            #bPaginate = FALSE,
            dom = 'Bfrtip',
            buttons = list(I('colvis'), c('excel', 'print'))
            )
          )


```

All Delivery-Racc
===============================================================================

```{r dettaglio, echo=FALSE}
Delivery_Racc$Giro <- as.factor(Delivery_Racc$Giro)
Delivery_Racc$Arrivo <- as.factor(Delivery_Racc$Arrivo)
Delivery_Racc$CAP <- as.factor(Delivery_Racc$CAP)
Delivery_Racc$Seq <- as.factor(Delivery_Racc$Seq)
Delivery_Racc$Scadenza <- as.factor(Delivery_Racc$Scadenza)
Delivery_Racc$Postino <- as.factor(Delivery_Racc$Postino)

datatable(Delivery_Racc, 
          class = 'compact nowrap',
          filter = 'top',
          extensions = c('Buttons', 'Responsive'),
          options = list(
            pageLength = 14,
            dom = 'Bfrtip',
            buttons = list(I('colvis'), c('excel', 'print'))
            )
          )

```

